name: inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    expose:
      - "3306"
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
    networks:
      - docker-network

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file: .env
    expose:
      - "9000"
    volumes:
      - type: volume
        source: wordpress-data
        target: /var/www/html
    networks:
      - docker-network

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - type: volume
        source: wordpress-data
        target: /var/www/html
    networks:
      - docker-network

volumes:
  mariadb-data:
    name: mariadb-volume
  wordpress-data:
    name: wordpress-volume

networks:
  docker-network:
    name: inception-network
    driver: bridge
